do-time/dotime

src/main/java/com/jhd/dotime/tasks/controller/TaskController.java
src/main/java/com/jhd/dotime/tasks/entity/Task.java
src/main/java/com/jhd/dotime/tasks/repository/MemoryTaskRepository.java
src/main/java/com/jhd/dotime/tasks/repository/TaskRepository.java
src/main/java/com/jhd/dotime/tasks/service/TaskService.java
src/main/java/com/jhd/dotime/tasks/service/TaskServiceImpl.java
src/test/java/com/jhd/dotime/DotimeApplicationTests.java
src/test/java/com/jhd/dotime/tasks/repository/TaskRepositoryTest.java
src/test/java/com/jhd/dotime/tasks/service/TaskServiceTest.java

- Test 코드를 기반으로 기본 로직 작성
- Task객체와 crud 기능을 포함한 service 코드 작성
- Repo crud 작성
- 우선 Appconfig를 사용하서 bean에 등록했음

feat :[20230116][이현동] Service, Repo Test code 작성

---

build.gradle
src/main/java/com/jhd/dotime/tasks/controller/TaskController.java
src/main/java/com/jhd/dotime/tasks/repository/MemoryTaskRepository.java
src/main/java/com/jhd/dotime/tasks/service/TaskServiceImpl.java
src/test/java/com/jhd/dotime/tasks/controller/TaskControllerTest.java
src/test/java/com/jhd/dotime/tasks/repository/TaskRepositoryTest.java
src/test/java/com/jhd/dotime/tasks/service/TaskServiceTest.java

- appConfig 내용 삭제
- 생성자 주입
- controller test 미완성

feat :[20230118][이현동] DI 적용

---

build.gradle

- junit-vintage-engine 추가
- hamcrest-core
- 중복 의존성 제거
- 스프링 공식문서 참조

update: [20230207][변지훈] 테스트 의존성 추가

---

src/main/java/com/jhd/dotime/members/repository/MemberRepository.java
src/main/java/com/jhd/dotime/members/repository/MemberRepositoryImpl.java
src/main/java/com/jhd/dotime/members/service/MemberServiceImpl.java
src/test/java/com/jhd/dotime/members/repository/MemberRepositoryTest.java

feat: [20230212][변지훈] service 단위테스트 변경중

---

src/main/java/com/jhd/dotime/members/entity/Member.java
src/main/java/com/jhd/dotime/members/service/MemberServiceImpl.java
src/test/java/com/jhd/dotime/members/repository/MemberRepositoryTest.java

- import 변경 : org.junit.jupiter.api.Test, afterEach() 사용을 위해
- afterEach delete 미적용 해결 : deleteAll -> deleteAllBatch

update: [20230213][변지훈] 테스트 오류 해결

---

src/main/java/com/jhd/dotime/tasks/controller/TaskController.java
src/main/java/com/jhd/dotime/tasks/dto/TaskResponseDto.java
src/main/java/com/jhd/dotime/tasks/dto/TaskSaveRequestDto.java
src/main/java/com/jhd/dotime/tasks/dto/TaskUpdateRequestDto.java
src/main/java/com/jhd/dotime/tasks/repository/TaskRepository.java
src/main/java/com/jhd/dotime/tasks/service/TaskService.java
src/main/java/com/jhd/dotime/tasks/service/TaskServiceImpl.java
src/test/java/com/jhd/dotime/tasks/controller/TaskControllerTest.java

- Controller, Swagger적용
- Dto로 Data Mapping
- Service 로직 수정

feat :[20230214][이현동] Controller, Service 작성

---

src/main/java/com/jhd/dotime/members/controller/MemberController.java
src/main/java/com/jhd/dotime/members/dto/MemberResponseDto.java
src/main/java/com/jhd/dotime/members/entity/Member.java
src/main/java/com/jhd/dotime/members/service/MemberServiceImpl.java

회원가인, 회원 정보 조회 메서드까지 Swagger로 테스트 완료했습니다

update: [20230216][변지훈] transactional 추가, 로직 간략화

---

src/main/java/com/jhd/dotime/members/controller/MemberController.java
src/main/java/com/jhd/dotime/members/service/MemberService.java
src/main/java/com/jhd/dotime/members/service/MemberServiceImpl.java

member update, delete 컨트롤러 만들어서 swagger 테스트까지 마쳤습니다.

update, delete controller 추가

---

src/main/java/com/jhd/dotime/members/dto/MemberDto.java
src/main/java/com/jhd/dotime/tasks/dto/TaskSaveRequestDto.java
src/main/java/com/jhd/dotime/tasks/service/TaskServiceImpl.java
src/test/java/com/jhd/dotime/tasks/service/TaskServiceTest.java

feat :[20230217][이현동] Member 별로 Task 조회 및 생성

---

src/main/java/com/jhd/dotime/common/exception/CommonExceptionContext.java
src/main/java/com/jhd/dotime/common/exception/CustomException.java

feat: [20230220][이현동] CustomException Handler

---

src/test/java/com/jhd/dotime/members/repository/MemberRepositoryTest.java

update: [20230222][변지훈] Repository Test 수정중

---

src/main/java/com/jhd/dotime/common/ApiUtils.java

update: [20230220][변지훈] Class 설명 주석 추가

---

src/main/java/com/jhd/dotime/common/config/SecurityConfig.java

- 이전 버전 Spring Security 기본 설정 추가
- Role 미추가로 JWT개발 시 MEMBER entity에 Role 추가해 개발 진행 예정

feat: [20230307][변지훈] SpringSecurity Config 추가

---

src/main/java/com/jhd/dotime/hashtag/repository/HashTagRepository.java
src/main/java/com/jhd/dotime/hashtag/service/HashTagService.java
src/main/java/com/jhd/dotime/hashtag/service/HashTagServiceImpl.java
src/main/java/com/jhd/dotime/hashtag/service/TaskTagService.java
src/main/java/com/jhd/dotime/hashtag/service/TaskTagServiceImpl.java
src/main/java/com/jhd/dotime/tasks/controller/TaskController.java

- 현재 중복된 hashtag가 생성되어 있음.
- 중복된 hashtag 생성을 방지해야한다.

fix :[20230317][이현동] task 생성 -> hashtag, tasktag 생성

---

src/main/java/com/jhd/dotime/members/controller/MemberController.java
src/main/java/com/jhd/dotime/members/dto/MemberRequestDto.java
src/main/java/com/jhd/dotime/members/dto/MemberResponseDto.java
src/main/java/com/jhd/dotime/members/mapper/MemberMapper.java
src/main/java/com/jhd/dotime/members/service/MemberServiceImpl.java
src/test/java/com/jhd/dotime/members/mapper/MemberMapperTest.java

- Member -> MemberResponseDto 변경 메서드 추가

feat: [20230314][변지훈] MapStruct toDto 메서드 추가

---

src/test/java/com/jhd/dotime/hashtag/entity/HashTagTest.java

- HashTag Entity equals, hashcode 재정의 테스트

update: [20230402][변지훈] HashTag Entity 테스트 코드

---

src/main/java/com/jhd/dotime/tasks/entity/Task.java
src/test/java/com/jhd/dotime/tasks/repository/TaskRepositoryTest.java
src/test/resources/application-test.yml

fix: [20230405][이현동] repo test 작성 완료

---

build.gradle
src/main/java/com/jhd/dotime/auth/controller/AuthController.java
src/main/java/com/jhd/dotime/auth/dto/LoginDto.java
src/main/java/com/jhd/dotime/members/service/MemberService.java
src/main/java/com/jhd/dotime/members/service/MemberServiceImpl.java
src/main/java/com/jhd/dotime/tasks/dto/TaskDto.java
src/main/java/com/jhd/dotime/tasks/service/TaskServiceImpl.java

update: [20230409][변지훈] 오류 해결

---

src/main/java/com/jhd/dotime/chat/common/handler/WebSocketChatHandler.java
src/main/java/com/jhd/dotime/chat/dto/ChatRoomDto.java
src/main/java/com/jhd/dotime/chat/entity/Chat.java
src/main/java/com/jhd/dotime/chat/entity/ChatRoom.java
src/main/java/com/jhd/dotime/chat/repository/ChatRoomRepository.java
src/main/java/com/jhd/dotime/chat/service/ChatRoomService.java
src/main/java/com/jhd/dotime/chat/service/ChatRoomServiceImpl.java
src/main/java/com/jhd/dotime/chat/service/ChatService.java
src/main/java/com/jhd/dotime/chat/service/ChatServiceImpl.java
src/main/java/com/jhd/dotime/tasks/entity/Task.java
src/test/java/com/jhd/dotime/chat/repository/ChatRepositoryTest.java

- 채팅서비스 개발 현재 socket test해야함
- chat, chatroom간 필요한 서비스 및 컨트롤러 개발 요구

feat: [20230412][이현동] Websocket config and Chat service

---

src/main/java/com/jhd/dotime/chat/controller/ChatController.java
src/main/java/com/jhd/dotime/chat/service/ChatRoomService.java
src/main/java/com/jhd/dotime/chat/service/ChatRoomServiceImpl.java
src/main/java/com/jhd/dotime/chat/service/ChatServiceImpl.java

- 채팅서비스 개발 현재 socket test해야함
- chat, chatroom간 필요한 서비스 및 컨트롤러 개발 요구

feat: [20230421][이현동] Websocket config and Chat service

---

src/main/java/com/jhd/dotime/tasktime/controller/AllocationTimeController.java
src/main/java/com/jhd/dotime/tasktime/dto/AllocationTimeDto.java
src/main/java/com/jhd/dotime/tasktime/dto/AllocationType.java
src/main/java/com/jhd/dotime/tasktime/service/AllocationTimeServiceImpl.java

- enum 추가
- 여러 타입의 할당 시간이 리스트형식의 request 로 들어올 수 있도록 수정

update: [20230425][변지훈] AllocationTimeDto 변경중

---

src/main/java/com/jhd/dotime/tasks/dto/TaskDto.java
src/main/java/com/jhd/dotime/tasks/entity/Task.java
src/main/java/com/jhd/dotime/tasktime/controller/AllocationTimeController.java
src/main/java/com/jhd/dotime/tasktime/dto/AllocationCategory.java
src/main/java/com/jhd/dotime/tasktime/dto/AllocationTimeDto.java
src/main/java/com/jhd/dotime/tasktime/entity/AllocationTime.java
src/main/java/com/jhd/dotime/tasktime/entity/TaskTimeLog.java
src/main/java/com/jhd/dotime/tasktime/mapper/AllocationTimeMapper.java
src/main/java/com/jhd/dotime/tasktime/service/AllocationTimeService.java
src/main/java/com/jhd/dotime/tasktime/service/AllocationTimeServiceImpl.java

- MySQL 예약어 오류로 AllocationTime 필드명 변경 type -> category, time -> hour
- 리스트형식의 request 입력 및 저장 로직 개발중

update: [20230426][변지훈] AllocationTimeDto 변경중
